# Site settings
title: Phil Cheng Design
email: chengp89@gmail.com
description: # this means to ignore newlines until "baseurl:"
  Just me designing and building stuff. Thanks for looking. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://philcheng.com" # the base hostname & protocol for your site
# twitter_username: gugujee
github_username:  philcheng
dribbble_username: philcheng

# Build settings
markdown: kramdown
