# Site settings
title: Phil Cheng Design
email: chengp89@gmail.com
description: # this means to ignore newlines until "baseurl:"
  Phil is an Atlanta based Industrial and UX designer. Discover his work and connect with him through the various outlets on this site. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://philcheng.com" # the base hostname & protocol for your site
# twitter_username: gugujee
github_username:  philcheng
dribbble_username: philcheng

# Build settings
markdown: kramdown
